(require 'js2-mode)
(add-to-list 'auto-mode-alist '("\\.js\\'"   . js2-mode))
(add-to-list 'auto-mode-alist '("\\.json\\'" . js2-mode))
(set-default 'js2-basic-offset 2)
(set-default 'js2-mirror-mode  nil)
(set-default 'js2-mode-escape-quotes  nil)
(define-key js2-mode-map (kbd "C-M-p") 
  (lambda () 
    (interactive) 
    (js2-beginning-of-defun)))
(define-key js2-mode-map (kbd "C-M-n") 
  (lambda () 
    (interactive) 
    (js2-end-of-defun)))
(define-key js2-mode-map (kbd "C-c m") 'js2-mark-defun)
